from __future__ import annotations
import numpy as np
from symatom import repS

from .encoders import AtomOrbitEncoderRegistry, OrbitSpec
from .encoders.phase2_encoder import Phase2EncoderFactory
from .describe import SegmentInfo, _orbit_example



def encode_and_describe(
    plan,
    event: dict | None,
    registry: AtomOrbitEncoderRegistry | None = None,
    phase2_factory: Phase2EncoderFactory | None = None,
) -> tuple[np.ndarray, list[SegmentInfo]]:
    """
    Core encoding function.  Runs the full two-phase encoding and simultaneously
    collects a SegmentInfo descriptor for every segment produced.

    Returns (values, segments) where:
      values   — 1-D float64 numpy array (the permutation-invariant embedding).
                 When event is None, values is a zero array of the correct length
                 (useful for describe-only callers that discard it).
      segments — list[SegmentInfo] mirroring the structure of values exactly.

    Passing event=None is the describe-only mode: segment lengths and metadata
    are computed identically (they are purely algebraic / registry-derived), but
    no atom evaluations are performed and the values array contains zeros.
    describe_encoding() uses this mode so that both functions share exactly one
    code path.

    Phase 1 (registry): metadata sourced from the registry's assess() responses.
    Phase 2 (phase2_factory): a Phase2EncoderFactory built from the hierarchical
      OverlapBlockEncoderFactory → row-pair factories chain.  When None, Phase 2
      is skipped entirely.

    Note: the diagnostic print in Phase 1 is temporary scaffolding.
    """
    fo_list = repS(plan.context, plan.operations)
    types   = plan.context.types

    parts    = []
    segments = []
    cursor   = 0

    # ------------------------------------------------------------------
    # Phase 1: encode each FlavouredOperator orbit.
    # ------------------------------------------------------------------
    for fo in fo_list:
        assert fo.count_of_atoms_one_per_sign() > 0, "No FlavouredOperator generated by repS should have an empty orbit."

        if registry is not None:
            spec       = OrbitSpec.from_flavoured_operator(fo)
            capable    = registry.query_all(spec, plan)
            chosen_enc = min(capable, key=lambda enc: enc.output_dim)
            length = chosen_enc.output_dim
            if event is not None:
                result = chosen_enc.encode(event)
                assert len(result.values) == length
                parts.append(result.values)
            else:
                parts.append(np.zeros(length, dtype=np.float64))
            segments.append(SegmentInfo(
                kind        = "ORBIT",
                start       = cursor,
                length      = length,
                op_u        = fo.operation.name,
                flavour_u   = tuple(fo.flavour.counts),
                method_name = chosen_enc.method_name,
                example     = _orbit_example(fo.operation.name, fo.flavour.counts, types),
            ))
            cursor += length

    # ------------------------------------------------------------------
    # Phase 2: compressed pair encoding.
    # ------------------------------------------------------------------
    if phase2_factory is not None:
        phase2_enc = phase2_factory.build(plan)
        if event is not None:
            result = phase2_enc.encode(event)
            parts.append(result.values)
        else:
            parts.append(np.zeros(phase2_enc.output_dim, dtype=np.float64))
        segments.extend(phase2_enc.describe(start_offset=cursor))
        cursor += phase2_enc.output_dim

    values = np.concatenate(parts) if parts else np.array([], dtype=float)
    return values, segments


def encode(
    plan,
    event: dict,
    registry: AtomOrbitEncoderRegistry | None = None,
    phase2_factory: Phase2EncoderFactory | None = None,
) -> np.ndarray:
    """
    Encode a physics event as a permutation-invariant vector.
    See encode_and_describe() for full documentation of the two-phase algorithm.
    Returns a 1-D float64 numpy array.
    """
    values, _segments = encode_and_describe(plan, event, registry, phase2_factory)
    return values


def describe_encoding(
    plan,
    registry: AtomOrbitEncoderRegistry | None = None,
    phase2_factory: Phase2EncoderFactory | None = None,
) -> list[SegmentInfo]:
    """
    Return a list of SegmentInfo objects describing the full structure of the
    vector produced by encode(plan, event, registry, phase2_factory).

    Delegates to encode_and_describe(plan, event=None, ...) — the single
    authoritative code path — and discards the (zero) values array.
    """
    _, segments = encode_and_describe(plan, event=None, registry=registry, phase2_factory=phase2_factory)
    return segments


