from __future__ import annotations
from symatom.context import Plan
from symatom.rep import PairFlavour
from .eval import evaluate


def eval_pair_orbit(pf: PairFlavour, plan: Plan, event: dict) -> list:
    """
    Return the complex numbers z_k = eval(u'_k, E) + i*eval(v'_k, E) for
    every atom-pair (u'_k, v'_k) in the G-orbit of the canonical
    representative of this PairFlavour.

    Returns pf.orbit_size(group_sizes) values.  Used as the brute-force
    reference and in group-theory tests; encode() uses eval_pair_orbit_positive
    instead.
    """
    return [
        complex(evaluate(u, event), evaluate(v, event))
        for u, v in plan.orbit_enumerator.orbit_elements(pf, plan.context)
    ]


def eval_single_orbit(fo, plan: Plan, event: dict) -> list:
    """
    Return eval(u, event) for every atom u in the orbit of a single
    FlavouredOperator fo.

    Uses fo.atoms() directly — no pair machinery needed.  The returned values
    are real scalars; for ANTISYMMETRIC operations both sign=+1 and sign=-1
    atoms are included (fo was created by repL with signed=True), so the list
    contains {a_k, -a_k} pairs.

    Used in Phase 1 of encode() to sort-encode the single-atom orbit before
    processing pair associations.
    """
    return [evaluate(atom, event) for atom in fo.atoms()]


def eval_single_orbit_compressed(fo, plan: Plan, event: dict) -> list:
    """
    Return Phase 1 values for fo, exploiting sign compression (5c) for
    ANTISYMMETRIC operations.

    ANTISYMMETRIC: the orbit under repL contains pairs {+u, -u} for every
    label combination, so eval values come in {y, -y} pairs.  Only the
    sign=+1 atoms are evaluated, and their absolute values are returned.
    This is permutation-invariant: label permutations may swap which atom
    carries sign=+1 vs -1, but |eval| is unchanged, and the multiset
    {|y_i|} is invariant.  Returns fo.count() // 2 values.

    SYMMETRIC / UNSTRUCTURED: all atoms have sign=+1 and the full eval
    list is returned (identical to eval_single_orbit).  Returns fo.count()
    values.

    The distinction is made entirely from fo.operation.argument_symmetry —
    never from the eval values themselves.
    """
    from symatom.atoms import ArgumentSymmetry
    if fo.operation.argument_symmetry == ArgumentSymmetry.ANTISYMMETRIC:
        return [abs(evaluate(atom, event)) for atom in fo.atoms() if atom.sign == +1]
    return [evaluate(atom, event) for atom in fo.atoms()]


def _is_self_pair(pf) -> bool:
    """True if every atom-pair (u_k, v_k) in this PairFlavour pairs an atom with itself.

    Condition: same operation, same flavour counts, and full (maximum) overlap.
    Under this condition z_k = eval(u_k) + i*eval(u_k) = (1+i)*a_k, which is
    entirely determined by Phase 1 orbit storage — no new information is added.
    """
    return (pf.op_u == pf.op_v and
            pf.flavour_u.counts == pf.flavour_v.counts and
            tuple(pf.overlap) == tuple(pf.flavour_u.counts))


def eval_pair_orbit_positive(pf: PairFlavour, plan: Plan, event: dict) -> list:
    """
    Return z_k = eval(u_k, E) + i*eval(v_k, E) for the pf.count() canonical
    positive label assignments of this PairFlavour.

    For each label assignment (lu, lv) generated by the PairFlavour combinatorial
    structure, both atoms are constructed with sign=+1 using their sorted-labels
    canonical form.  This always yields exactly pf.count(group_sizes) values
    regardless of which operations are ANTISYMMETRIC.

    The construction
    ----------------
    For each (shared, u-only, v-only) label partition per group (as enumerated
    by PairFlavour.count), labels_u and labels_v are assembled by concatenation.
    Since shared and *-only labels come from combinations() they may not be
    globally sorted.  Atom(op, labels, +1) normalises labels into sorted order
    and absorbs the permutation parity into the sign for ANTISYMMETRIC operations.
    Re-constructing with the now-sorted labels and sign=+1 yields the canonical
    positive atom (sign=+1 guaranteed because sorted labels have perm_sign=1).

    This approach is independent of the orbit enumerator.  The values produced
    are identical to the multiset that the old OrbitUnion-based (++ filter)
    approach produced: in both cases the result is
        { eval_fn(sorted_label_vecs_u) + i * eval_fn(sorted_label_vecs_v) }
    for each distinct (sorted_lu, sorted_lv) label assignment.

    Why this subset is sufficient for encoding (see _embed_compressed in
    encode.py): forming the symmetry-class-appropriate invariant multiset from
    these n values (e.g. {z_k, conj(z_k)} for SYM×ANTISYM) recovers the full
    permutation-invariant polynomial with its forced-real / forced-zero
    coefficient structure, yielding the same information as the full orbit
    embedding at a fraction of the cost.
    """
    from itertools import combinations as _combs, product as _iproduct
    from symatom.atoms import Atom

    per_group = []
    for g, ku, kv, s in zip(
        plan.context.groups,
        pf.flavour_u.counts,
        pf.flavour_v.counts,
        pf.overlap,
    ):
        group_choices = []
        for shared in _combs(g.labels, s):
            shared_set = set(shared)
            rest1 = [l for l in g.labels if l not in shared_set]
            for u_only in _combs(rest1, ku - s):
                u_only_set = set(u_only)
                rest2 = [l for l in rest1 if l not in u_only_set]
                for v_only in _combs(rest2, kv - s):
                    group_choices.append((shared, u_only, v_only))
        per_group.append(group_choices)

    result = []
    for combo in _iproduct(*per_group):
        labels_u = tuple(lbl for shared, u_only, _ in combo for lbl in shared + u_only)
        labels_v = tuple(lbl for shared, _, v_only in combo for lbl in shared + v_only)
        # Normalise: Atom sorts labels and absorbs perm parity into sign.
        # Re-construct from sorted labels with sign=+1 to get canonical positive form.
        u_norm = Atom(pf.op_u, labels_u, sign=+1)
        v_norm = Atom(pf.op_v, labels_v, sign=+1)
        u_pos  = Atom(pf.op_u, u_norm.labels, sign=+1)   # sorted labels → sign=+1
        v_pos  = Atom(pf.op_v, v_norm.labels, sign=+1)
        result.append(complex(evaluate(u_pos, event), evaluate(v_pos, event)))

    return result
